# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb4093e795bc278fd98b87c622c950b802fbae3a6b8f1e95a70c3a02cee962bd7301b10c3bc0e589f02e94f40ddc4023f0ae32bab5e9935f709bba7943403567

test:
  secret_key_base: d6a7b8573229fc515d01ee6b815569530580bda48e9117815240ed7cc1fbfa080dbc56318c80ffae71c1ee3b0238df0be3dbfe03d7f19f50b2625a9430e26fb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
